version: '3.7'
services:
  php-fpm:
    build:
      context: ./docker/web
    user: ${uid}:${gid}
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      XDEBUG_CONFIG: remote_enable=1 remote_mode=req remote_host=${ip} remote_port=9000 idekey=phpstorm remote_connect_back=0
      PHP_IDE_CONFIG: "serverName=docker"
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./docker/web/default.conf
        target: /etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - type: bind
        source: ./
        target: /home/hostuser/app
    environment:
      UID: ${uid}
      GID: ${gid}
