#!/usr/bin/env bash
set -e

if [ -z "${UID}" ]; then
    echo "The UID env variable is required."
    exit 1
fi

if [ -z "${GID}" ]; then
    echo "The GID env variable is required."
    exit 1
fi

groupmod -g ${GID} hostuser
usermod -u ${UID} hostuser  > /dev/null 2>&1

exec runuser -u hostuser "$@"